### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by pur-suit** [creinders/ChimeraMix#1]
Hello, when I run the code according to readme, there are errors of TypeError:' nonetype' object is not callable and EOFError: Ran out of input. After debugging, I find that the input dataloader is empty. Could you please give the codes of trainer_loader and val_loader in trainer.fit (model, data module = dm)?

**Comment by creinders** [comment]
Hi,

the train_dataloader and val_dataloader are created here: https://github.com/creinders/ChimeraMix/blob/a5aec8a7f69cb2b7f486bc2adfbfbcf15cd77049/datasets/vision_data_module.py#L163-L182

Could you please provide the output log and the stack trace?

**Comment by creinders** [comment]
I verified the training pipeline, and the training works as usual. Please feel free to reopen the issue if you still encounter problems.
